### ISSUE TITLE
I'm not able to configure -config.yml file

### ISSUE THREAD

**Issue by jairamshegde** [ritijjain/pudhina-fresh#15]
I really liked your theme. But I'm not able to figure out how to properly update _config.yml file. I have jekyll and other requirements up and running. can you make simple video on this? please...

**Comment by ritijjain** [comment]
Hello @jairamshegde, I have updated the [docs](https://ritijjain.github.io/pudhina-fresh/2020/07/01/docs.html) to include some information on how to work with `_config.yml`. I won't be able to make a video on this anytime soon but I found this [playlist](https://www.youtube.com/watch?v=pxua_1vyFck&list=PLLAZ4kZ9dFpOPV5C5Ay0pHaa0RJFhcmcB&index=4&ab_channel=MikeDane) on YouTube which should explain everything.

**Comment by jairamshegde** [comment]
thank you for response. I did the same thing but description is not updating, only site title is updating.

**Comment by ritijjain** [comment]
@jairamshegde Description on the main page can be changed in `index.html`.
