### ISSUE TITLE
How to add new social link

### ISSUE THREAD

**Issue by emrecoban** [ritijjain/pudhina-fresh#19]
Hey!

I try to add new social icon to the theme, but I cannot.
I tried to add the code in _includes/page/header.html, but it doesn't work:
`{% if site.author.scholar %}
<a href="https://scholar/{{ site.author.scholar }}" class="social-links__entry" target="_blank">
<i class="fas fa-envelope-square"></i>
</a>
{% endif %}`

**Comment by ritijjain** [comment]
@emrecoban This bit of code seems correct. I think you have made a mistake elsewhere, I can check if you share your repository.

**Comment by emrecoban** [comment]
Sorry, my mistake. I restarted server in localhost, and then the icon was displayed.
Thank you.
