### ISSUE TITLE
Auto tagging

### ISSUE THREAD

**Issue by emrecoban** [ritijjain/pudhina-fresh#20]
Hi,

> Tag pages must be manually created under pages/tags. Each tag page should include front matter in this format:

I want jekyll to add tags auto. How can I do that? I saw some solution, but I'm confused. I look for easy way to add tags.

**Comment by ritijjain** [comment]
Hey @emrecoban, such functionality would require us to use a custom Jekyll plugin which GitHub pages currently does not support. 

However, custom plugins can be used if you build the site locally or deploy to services like [Netlify](https://www.netlify.com/) which do support plugins. In this case, you can consider using the [jekyll-tagging](https://github.com/pattex/jekyll-tagging) plugin.

If you don't have many tags, it is easiest to just do it manually. Also, this theme uses the style data you define on the tag page to style the tags elsewhere on the site so you would have to create those pages anyway.

**Comment by emrecoban** [comment]
Thank you @ritijjain for clear answer.  I might write a bot which make tag pages auto instead of me.
