### ISSUE TITLE
More syntax highlighting issues

### ISSUE THREAD

**Issue by jaxxstorm** [ritijjain/pudhina-fresh#22]
Hello! You may remember me #4

I updated to the latest theme, but it seems syntax highlighting broke yet again :(

It renders absolutely fine locally with `jekyll serve` but as soon as it gets into github pages, everything breaks.

Any suggestions? Happy to throw a few $ your way to thank you for the help

**Comment by ritijjain** [comment]
Hello @jaxxstorm, it looks like the method which loads the code block styles is deprecated and has been replaced by a new method. I have created a pull request that should fix it for your site. Let me know if it works.

This is the error message the fix is based on:
```
highlight.min.js:106: Deprecated as of 10.6.0. initHighlightingOnLoad() deprecated.  Use highlightAll() now.
```

Coffees always help, you can use [ko-fi](https://ko-fi.com/ritijjain). Thank you!

**Comment by jaxxstorm** [comment]
Thanks for much for the speedy response!

That doesn't appear to have immediately fixed the issue. Checking the page source, I see lots of `rouge` references:

```
<code class="language-plaintext highlighter-rouge">try</code> 
```

Do I need to disable rouge somehow?

**Comment by jaxxstorm** [comment]
I compared the generated code locally with the gh pages code, and everything seems to be exactly the same. I purged my CDN cache to see if that helped, and no dice :-(

**Comment by jaxxstorm** [comment]
Okay, i switched away from github pages to cloudflare pages, and everything is working great! thanks for the help!

**Comment by jaxxstorm** [comment]
@ritijjain just as a heads up, when I try to dojate I get 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/1622940/166178233-bc2cb097-a4e9-45b2-a9f3-f85ab5c6d47f.png">


You may want to consider another donation mechanism
