### ISSUE TITLE
Switch back to rouge highlighting

### ISSUE THREAD

**Issue by jaxxstorm** [ritijjain/pudhina-fresh#4]
Hey there! Firstly, thanks for the amazing theme, it rocks!

I'm trying to use it with GitHub pages, but highlight.js is not playing nice. You can see an example here:

https://www.leebriggs.co.uk/blog/2018/10/16/using-kubeless-for-kubernetes-events.html

Any tips? Is it possible to disable highlights.js and use the default rouge syntax highlighter?

**Comment by ritijjain** [comment]
Hello @jaxxstorm, thanks for using this theme!

This is very weird because I am [using](https://ritijjain.com/2020/09/12/pudhina-fresh.html) the same theme with GitHub pages without any problems with highlight.js.

I inspected the example post, the code block class seems to be incomplete, it should render as `class="language-python hljs"` instead of just `class="language-python"`. Hljs assets are loading properly, but they are not being called correctly in the HTML. So the problem is definitely something to do with GitHub pages/Jekyll site generation.

I cloned your repo and tried changing a few things. Removing this bit of code you added seems to be fixing things.
```
kramdown:
   syntax_highlighter_opts:
      disable : true
```
Try this out and let me know how it goes.

**Comment by jaxxstorm** [comment]
Thanks for the speedy response! I've yanked the config and purged the CDN cache and unless I'm mistaken it's still rendering without the highlights, which is very strange

**Comment by ritijjain** [comment]
I think it would be best to build your Jekyll site locally then. You can: 

1. Remove `_site` from .gitignore.
2. Add an empty file named `.nojekyll` to your branch
4. Locally [install Jekyll](https://jekyllrb.com/docs/installation/)
3. run `bundle exec jekyll build` locally and then push your changes.

**Comment by jaxxstorm** [comment]
Gave that a try, seemed to break completely :-D 

Is there a way to disable the highlights.js and just use the default rouge highlighter?

**Comment by ritijjain** [comment]
To use rouge:
* Choose your favorite Pygments css style for highlighting from [here](http://jwarby.github.io/jekyll-pygments-themes/languages/python.html) and download it. This should go in `assets/css`.
* Link your css in the `_includes/externals/styling.html` file:
```
<link rel="stylesheet" href="{{ site.baseurl }}/assets/css/<your chosen css>">
```
* Also remove or comment out all the highlight.js assets:
```
<!--Highlight.js
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.3.2/build/styles/default.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.3.2/build/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
-->
```
* Remove/change inline styles from `assets/css.main.css`, these were made to be compatible with highlight.js
```
/*
  code {
    font-size: 90%;
    border-radius: 3px;
    padding: 2px 4px;
    background: #f0f0f0;
    color: #444 }

    **/
```
* Code blocks should work now! Also, keep in mind Rouge does not support automatic language detection so you will have to define the language with every code block to get the correct styles.

In future updates, I will add options to chose from multiple highlight tools.

**Comment by jaxxstorm** [comment]
Okay, that seems to have gotten my syntax highlighting back, thank you! I'll close this out, really appreciate the support!

**Comment by jaxxstorm** [comment]
Also, please let me know if I can buy you a coffee to support your work!

**Comment by ritijjain** [comment]
@jaxxstorm That would be really nice! You can use [ko-fi](https://ko-fi.com/ritijjain) or [liberapay](https://liberapay.com/ritijjain).
